FEATURE_SETS = {
    "history": ["light"],
    "history_time": [
        "light",
        "hour_sin",
        "hour_cos",
        "dow_sin",
        "dow_cos",
        "month_sin",
        "month_cos",
        "worktime",
    ],
    "history_env": [
        "light",
        "lux",
        "temp",
        "rh",
        "hour_sin",
        "hour_cos",
        "dow_sin",
        "dow_cos",
        "month_sin",
        "month_cos",
        "worktime",
    ],
    "full": [
        "light",
        "plug",
        "ac",
        "lux",
        "temp",
        "rh",
        "hour_sin",
        "hour_cos",
        "dow_sin",
        "dow_cos",
        "month_sin",
        "month_cos",
        "worktime",
    ],
}
